# SEO settings
title: "Lauszus"
description: "Personal website"
keywords: "Lauszus, Electronics, Embedded, Robotics, Engineer"
url: http://lauszus.com
baseurl: null

google_analytics: UA-97396734-1
repo: http://github.com/lauszus/lauszus.github.io
disqus_shortname: "lauszusthemes"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 4
paginate_path: "projects/page/:num/"
comments: false

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Kristian Sloth Lauszus
  job      : Electrical Engineer
  bio      : "I have a passion, drive and skill set in the field of Electrical Engineering. My main interests are embedded devices and control systems."
  avatar   : https://www.gravatar.com/avatar/04aa3aec79f1845a03eeb74681b57204?s=200
  email    : lauszus@gmail.com
  url      : http://lauszus.com
  github   : http://github.com/Lauszus
  twitter  : http://twitter.com/Lauszus
  facebook : http://facebook.com/kristian.lauszus
  linkedin : http://linkedin.com/in/kristian-sloth-lauszus
  youtube  : https://www.youtube.com/user/kslauszus

# Social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@lauszus"

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# navbar pages
navbar:
  - slug : projects
    title: Projects
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
