
# SEO settings
title: "Lauszus"
description: "Personal website"
keywords: "Lauszus, Electronics, Embedded, Robotics"
url: http://lauszus.com
baseurl: null

repo: http://github.com/lauszus/lauszus.github.io
disqus_shortname: "lauszusthemes"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Kristian Sloth Lauszus
  job      : Electrical Engineer
  bio      : "I have a passion, drive and skill set in the field of Electrical Engineering. My main interests are embedded devices and control systems."
  thumb    : /images/author.jpg
  email    : lauszus@gmail.com
  url      : http://lauszus.com
  github   : http://github.com/Lauszus
  twitter  : http://twitter.com/Lauszus
  facebook : http://facebook.com/kristian.lauszus
  linkedin : http://linkedin.com/in/kristian-sloth-lauszus

# Social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@lauszus"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
